USE master
GO
if exists (select * from sysdatabases where name='TAKESHI')
	DROP DATABASE TAKESHI
GO

CREATE DATABASE TAKESHI
GO
USE TAKESHI
GO

DROP DATABASE TAKESHI;

----- Create Tables -----

CREATE TABLE POTION (
 NAME CHAR(100) NOT NULL,
 AFFECTING_FIELD CHAR(13) CHECK (AFFECTING_FIELD IN 
 ( 'HealthPoints','Strength','Mana'))NOT NULL,
 AFFECTING_VALUE INTEGER NOT NULL
);

CREATE TABLE Armors (
 ID int NOT NULL,
 NAME CHAR(100) NOT NULL,
 ARMOR_POINTS INTEGER  NOT NULL,
 POTION_SLOTS INTEGER NOT NULL
);

select * from Armors
drop table Armors;

CREATE TABLE WEAPON (
 NAME CHAR(100) NOT NULL,
 DAMAGE_POINTS INTEGER  NOT NULL,
 HERO_CLASS_TYPE CHAR(13) CHECK (HERO_CLASS_TYPE IN 
 ( 'Mele','Range','Mage'))NOT NULL
);


CREATE TABLE HERO (
 NAME CHAR(100) NOT NULL,
 HEALTH_POINTS INTEGER NOT NULL,
 SRENGHT INTEGER NOT NULL,
 ARMOR CHAR(100) NOT NULL,
 --ABILITIES CHAR(100) NOT NULL,
 PRIMARY_WEAPON CHAR(100) NOT NULL
);




----- Create Constraints -----
ALTER TABLE POTION ADD CONSTRAINT PK_POTION PRIMARY KEY(NAME);
ALTER TABLE Armors ADD CONSTRAINT PK_ARMOR PRIMARY KEY(ID);
ALTER TABLE WEAPON ADD CONSTRAINT PK_WEAPON PRIMARY KEY(NAME);

--ALTER TABLE MOVIE ADD CONSTRAINT FK_MOVIE_MOVIEEXEC FOREIGN KEY(PRODUCERC#) REFERENCES MOVIEEXEC(CERT#);